apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: shopwise
  annotations:
    # This annotation links the K8s ServiceAccount to the IAM role
    # When a pod uses this SA, it gets AWS credentials automatically
    eks.amazonaws.com/role-arn: "arn:aws:iam::617162869021:role/shopwise-dev-backend-pod-role"
